Cphayim/enc

- CHANGELOG.md
- CHANGELOG.zh-CN.md
- packages/base/package.json
- packages/react/package.json
- packages/shared/package.json
- packages/vue-element-plus/package.json
- packages/vue-vant/package.json
- packages/vue/package.json
> chore: release v0.1.1

- packages/vue-vant/src/components/form/items/CheckboxFormItem.vue
- packages/vue-vant/src/components/form/items/RadioFormItem.vue
- playgrounds/vue/src/views/form/Controller.vue
fix `EncCheckbox` and `EncRadio` component style variables.
- @cphayim-enc/vue-vant
> fix(vant): style variables

- packages/vue/src/hooks/__tests__/use-form-data.spec.ts
- packages/vue/src/hooks/__tests__/use-form-items.spec.ts
- packages/vue/src/hooks/__tests__/use-form.spec.ts
- packages/vue/src/hooks/use-form-data.ts
- packages/vue/src/hooks/use-form-items.ts
- packages/vue/src/hooks/use-form.ts
- `@cphayim-enc/vue`
- add `useFormData` and `useFormItems` hooks
- `useForm` is a combination of the above hooks
> feat(vue): split `useForm` to `useFormData` and `useFormItems`

- packages/vue/package.json
- packages/vue/src/hooks/__tests__/use-pagination.spec.ts
- packages/vue/src/hooks/use-pagination.ts
- pnpm-lock.yaml
> feat(vue): add `usePagination` hook

- CHANGELOG.md
- CHANGELOG.zh-CN.md
- packages/base/package.json
- packages/react/package.json
- packages/shared/package.json
- packages/vue-element-plus/package.json
- packages/vue-vant/package.json
- packages/vue/package.json
> chore(release): test version v0.1.10

- packages/vue-vant/src/components/layout/Layout.vue
**@cphayim-enc/vue-vant**
- `EncLayout` component add `onBack` props, can use it to define the logic of `backArrow`
> feat(vant): `EncLayout` add `onBack` prop

- CHANGELOG.md
- CHANGELOG.zh-CN.md
- packages/base/package.json
- packages/react/package.json
- packages/shared/package.json
- packages/vue-element-plus/package.json
- packages/vue-vant/package.json
- packages/vue/package.json
> chore(release): test version v0.1.11

- packages/vue-vant/src/components/layout/Layout.vue
**@cphayim-enc/vue-vant**
- `EncLayout` component add `header-title` slot
> feat(vant): `EncLayout` component add `header-title` slot

- CHANGELOG.md
- CHANGELOG.zh-CN.md
- packages/base/package.json
- packages/react/package.json
- packages/shared/package.json
- packages/vue-element-plus/package.json
- packages/vue-vant/package.json
- packages/vue/package.json
> chore(release): test version v0.1.12

- CHANGELOG.md
- CHANGELOG.zh-CN.md
- packages/base/package.json
- packages/react/package.json
- packages/shared/package.json
- packages/vue-element-plus/package.json
- packages/vue-vant/package.json
- packages/vue/package.json
> chore(release): test version 0.1.13

- packages/vue-element-plus/src/components/form/upload/UploadFormItem.vue
- packages/vue-vant/src/components/form/upload/UploadFormItem.vue
fixes #59 
- **@cphayim-enc/vue-vant**
- **@cphayim-enc/vue-element-plus**
- fixed logical judgment of `uploadAccept`
> fix(element,vant): logical judgment of `uploadAccept`

- CHANGELOG.md
- CHANGELOG.zh-CN.md
- packages/base/package.json
- packages/react/package.json
- packages/shared/package.json
- packages/vue-element-plus/package.json
- packages/vue-vant/package.json
- packages/vue/package.json
> chore(release): test version v0.1.15

- CHANGELOG.md
- CHANGELOG.zh-CN.md
- packages/base/package.json
- packages/extension-form-editor/package.json
- packages/extension-vue-form-editor/package.json
- packages/react/package.json
- packages/shared/package.json
- packages/vue-element-plus/package.json
- packages/vue-vant/package.json
- packages/vue/package.json
- playgrounds/vue/package.json
- pnpm-lock.yaml
> chore(release): v0.2.0

- CHANGELOG.md
- CHANGELOG.zh-CN.md
- packages/base/package.json
- packages/extension-form-editor/package.json
- packages/extension-vue-form-editor/package.json
- packages/react/package.json
- packages/shared/package.json
- packages/vue-element-plus/package.json
- packages/vue-vant/package.json
- packages/vue/package.json
> chore(release): v0.2.1

- CHANGELOG.md
- CHANGELOG.zh-CN.md
- packages/base/package.json
- packages/extension-form-editor/package.json
- packages/extension-vue-form-editor/package.json
- packages/react/package.json
- packages/shared/package.json
- packages/vue-element-plus/package.json
- packages/vue-vant/package.json
- packages/vue/package.json
> chore(release): v0.2.2

- CHANGELOG.md
- CHANGELOG.zh-CN.md
- packages/base/package.json
- packages/extension-form-editor/package.json
- packages/extension-vue-form-editor/package.json
- packages/react/package.json
- packages/shared/package.json
- packages/vue-element-plus/package.json
- packages/vue-vant/package.json
- packages/vue/package.json
> chore(release): v0.2.3

- packages/vue-element-plus/src/upstream.ts
- packages/vue-vant/src/upstream.ts
- packages/vue/src/components/index.ts
- packages/vue/src/components/keep-alive-router-view/KeepAliveRouterView.vue
- packages/vue/src/components/keep-alive-router-view/index.ts
- packages/vue/src/index.ts
- **@cphayim-enc/vue**
- **@cphayim-enc/vue-element-plus**
- **@cphayim-enc/vue-vant**
- add `EncKeepAliveRouterView` component
> feat(vue): add `EncKeepAliveRouterView` component

- packages/vue-element-plus/src/styles/base.css
- **@cphayim-enc/vue-element-plus**
- a thin scrollbar style is provided by default
> refactor(element-plus): default scrollbar style

- CHANGELOG.md
- CHANGELOG.zh-CN.md
- packages/base/package.json
- packages/extension-form-editor/package.json
- packages/extension-vue-form-editor/package.json
- packages/react/package.json
- packages/shared/package.json
- packages/vue-element-plus/package.json
- packages/vue-vant/package.json
- packages/vue/package.json
> chore(release): v0.2.4

- CHANGELOG.md
- CHANGELOG.zh-CN.md
- packages/base/package.json
- packages/extension-form-editor/package.json
- packages/extension-vue-form-editor/package.json
- packages/react/package.json
- packages/shared/package.json
- packages/style/package.json
- packages/vue-element-plus/package.json
- packages/vue-vant/package.json
- packages/vue/package.json
> chore(release): v0.2.5

- packages/style/package.json
- packages/style/src/color.css
- packages/style/src/index.ts
- packages/style/src/rate.css
- packages/style/src/safe-area.css
- packages/style/src/style.css
- packages/vue-element-plus/package.json
- packages/vue-element-plus/src/upstream.ts
- packages/vue-vant/package.json
- packages/vue-vant/src/upstream.ts
- packages/vue/postcss.config.cjs
- packages/vue/src/components/index.ts
- packages/vue/src/components/transition/Fade.vue
- packages/vue/src/components/transition/Slide.vue
- packages/vue/src/components/transition/Transition.vue
- packages/vue/src/components/transition/hooks.ts
- packages/vue/src/components/transition/index.ts
- packages/vue/src/index.ts
- packages/vue/vite.config.ts
- pnpm-lock.yaml
- **@cphayim-enc/style**
- **@cphayim-enc/vue**
**@cphayim-enc/style**
- export `EncCSSVariables`
**@cphayim-enc/vue**
- implement `EncTransition`, can now use `EncTransition.Fade` and `EncTransition.Slide` components
> feat(style, vue): implement `EncTransition`, export `EncCSSVariables`

- CHANGELOG.md
- CHANGELOG.zh-CN.md
- packages/base/package.json
- packages/extension-form-editor/package.json
- packages/extension-vue-form-editor/package.json
- packages/react/package.json
- packages/shared/package.json
- packages/style/package.json
- packages/vue-element-plus/package.json
- packages/vue-vant/package.json
- packages/vue/package.json
> chore(release): v0.2.6

- packages/vue-element-plus/src/upstream.ts
- packages/vue-vant/src/upstream.ts
- **@cphayim-enc/vue-element-plus**
- **@cphayim-enc/vue-vant**
**@cphayim-enc/vue-element-plus**
**@cphayim-enc/vue-vant**
- export upstream components
> fix(element-plus,vant): export upstream components

- packages/vue/src/components/transition/Fade.vue
- packages/vue/src/components/transition/Zoom.vue
- packages/vue/src/components/transition/index.ts
- **@cphayim-enc/vue**
**@cphayim-enc/vue**
- add `EncTransition.Zoom` component
> feat(vue): implement `EncTransition.Zoom`

- packages/base/src/biz-form/helper.ts
- packages/extension-form-editor/src/biz/transformer.ts
- **@cphayim-enc/base**
**@cphayim-enc/base**
- `BizFormHelper` provides some utility functions
> feat(base): `BizFormHelper` utils

- CHANGELOG.md
- CHANGELOG.zh-CN.md
- packages/base/package.json
- packages/extension-form-editor/package.json
- packages/extension-vue-form-editor/package.json
- packages/react/package.json
- packages/shared/package.json
- packages/style/package.json
- packages/vue-element-plus/package.json
- packages/vue-vant/package.json
- packages/vue/package.json
> chore(release): v0.2.9

- .github/workflows/release.yml
- CHANGELOG.md
- CHANGELOG.zh-CN.md
- packages/base/package.json
- packages/extension-form-editor/package.json
- packages/extension-vue-form-editor/package.json
- packages/react/package.json
- packages/shared/package.json
- packages/style/package.json
- packages/vue-element-plus/package.json
- packages/vue-vant/package.json
- packages/vue/package.json
> chore(release): v0.2.10

- CHANGELOG.md
- CHANGELOG.zh-CN.md
- packages/base/package.json
- packages/extension-form-editor/package.json
- packages/extension-vue-form-editor/package.json
- packages/react/package.json
- packages/shared/package.json
- packages/style/package.json
- packages/vue-element-plus/package.json
- packages/vue-vant/package.json
- packages/vue/package.json
> chore(release): v0.2.11

- CHANGELOG.md
- CHANGELOG.zh-CN.md
- packages/base/package.json
- packages/extension-form-editor/package.json
- packages/extension-vue-form-editor/package.json
- packages/react/package.json
- packages/shared/package.json
- packages/style/package.json
- packages/vue-element-plus/package.json
- packages/vue-vant/package.json
- packages/vue/package.json
> chore(release): v0.2.13

- CHANGELOG.md
- CHANGELOG.zh-CN.md
- packages/base/package.json
- packages/extension-form-editor/package.json
- packages/extension-vue-form-editor/package.json
- packages/react/package.json
- packages/shared/package.json
- packages/style/package.json
- packages/vue-element-plus/package.json
- packages/vue-vant/package.json
- packages/vue/package.json
> chore(release): v0.3.0

- packages/base/src/form-analyzer/BizFormAnalyzer.ts
- packages/extension-vue-form-editor/src/components/form-edit-panel/right-panel/RightPanel.vue
- **@cphayim-enc/base**
- **@cphayim-enc/extension-vue-form-editor**
**@cphayim-enc/base**
- wrong type alias
**@cphayim-enc/extension-vue-form-editor**
- form editor right panel unexpectedly shows biz item
> fix(base,ex-form-editor): wrong type alias and form editor right panel display error

- packages/vue-element-plus/src/upstream.ts
- packages/vue-vant/src/upstream.ts
- packages/vue/package.json
- packages/vue/src/hooks/use-emitter.ts
- pnpm-lock.yaml
- **@cphayim-enc/vue**
**@cphayim-enc/vue**
- replace mitt with @ombro/mitten
> refactor(vue): use @ombro/mitten

- CHANGELOG.md
- CHANGELOG.zh-CN.md
- packages/base/package.json
- packages/extension-form-editor/package.json
- packages/extension-vue-form-editor/package.json
- packages/react/package.json
- packages/shared/package.json
- packages/style/package.json
- packages/vue-element-plus/package.json
- packages/vue-vant/package.json
- packages/vue/package.json
> chore(release): v0.3.2

- pnpm-lock.yaml
- vitest.config.ts
Reference https://github.com/vitest-dev/vitest/issues/3862
updated the inline configuration
> chore(config): update vitest config

- CHANGELOG.md
- CHANGELOG.zh-CN.md
- packages/base/package.json
- packages/extension-form-editor/package.json
- packages/extension-vue-form-editor/package.json
- packages/react/package.json
- packages/shared/package.json
- packages/style/package.json
- packages/vue-element-plus/package.json
- packages/vue-vant/package.json
- packages/vue/package.json
> chore(release): v0.3.3

- .github/workflows/docs.yml
- .gitignore
- docs/.vitepress/config.mts
- docs/api-examples.md
- docs/index.md
- docs/markdown-examples.md
- package.json
- pnpm-lock.yaml
> chore(vitepress): init vitepress

- playgrounds/vue/src/views/form-editor/index.vue
- playgrounds/vue/src/views/form/PreviewElementPlus.vue
- playgrounds/vue/src/views/form/PreviewVant.vue
Fix incorrect type imports in playground
> fix(pg): incorrect type imports
